{
 "title": "Alerts",
 "description": "Alerts from prometheus.",
 "tags": [ "alerts" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "30s,1m,5m,1h,6h,1d" },
   { "name": "service", "label": "service", "query": "label_values(ALERTS, instance)" },
   { "name": "job", "label": "job", "query": "label_values(ALERTS, job)" },
   {
    "name": "alertname",
    "label": "alertname",
    "query": "label_values(ALERTS, alertname)"
   },
   { "name": "alertstate", "label": "alertstate", "query": "firing, pending" },
   { "name": "severity", "label": "severity", "query": "label_values(ALERTS, severity)" }
  ]
 },
 "panels": [
  {
   "title": "Warning",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ALERTS{environment=~\"$environment\", service=~\"$service\", job=~\"$job\", alertname=~\"$alertname\", alertstate=~\"$alertstate\",severity=\"warning\"} > 0) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "High",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ALERTS{service=~\"$service\", job=~\"$job\", alertname=~\"$alertname\", alertstate=~\"$alertstate\",severity=\"high\"} > 0) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Critical",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ALERTS{service=~\"$service\", job=~\"$job\", alertname=~\"$alertname\", alertstate=~\"$alertstate\",severity=\"critical\"} > 0) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Max  Load Average 1m",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "max (node_load1)" }
   ]
  },
  {
   "title": "Min Memory Available",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(node_memory_MemAvailable_bytes)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Max Tcp Established",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(node_netstat_Tcp_CurrEstab)"
    }
   ]
  },
  {
   "title": "Prometheus HTTP Request Duration",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 17, "y": 0 },
   "format": "µs",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(http_request_duration_microseconds_sum{job=\"prometheus\"}[5m])) /  sum(irate(http_request_duration_microseconds_count{job=\"prometheus\"}[5m]))"
    }
   ]
  },
  {
   "title": "Prometheus Targets",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "count(up)" }
   ]
  },
  {
   "title": "Current Alert Table",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "count(ALERTS{instance=~\"$service\", job=~\"$job\", alertname=~\"$alertname\", alertstate=~\"$alertstate\"} == 1) by (instance,alertname,job,alertstate)",
     "legendFormat": "service: {{service}} environment: {{environment}} instance: {{instance}}  alertname: {{alertname}}   service: {{service}}"
    }
   ]
  },
  {
   "title": "Alert Graph",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "10s",
     "expr": "count(ALERTS{instance=~\"$service\", job=~\"$job\", alertname=~\"$alertname\", alertstate=~\"$alertstate\"} == 1) by (instance,alertname)",
     "legendFormat": "{{instance}}  {{alertname}}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "ALERTS{instance=~\"$service\", job=~\"$job\", alertname=~\"$alertname\", alertstate=~\"$alertstate\",severity=~\"$severity\"}",
     "labelSelector": "*",
     "legendFormat": "{{msg}}",
     "target": "Query",
     "type": "table"
    }
   ]
  }
 ]
}