{
 "title": "Alerts - Grafana",
 "description": "Alerts for Linux Nodes using prometheus and node_exporter. You can have alerts for Disk space, CPU and Memory. Also added a log of alerts and alert status.",
 "tags": [
  "alerts",
  "linux"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Alerts Status", "type": "alertlist", "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 } },
  { "title": "Alerts Log", "type": "alertlist", "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 } },
  {
   "title": "Linux Nodes Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100*(node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes) / node_memory_MemTotal_bytes",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Linux Nodes CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Linux Nodes Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bps", "label": "bps in (-) / bps out (+)" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total[1m])) by (instance) * 8",
     "legendFormat": "{{instance}} in"
    },
    {
     "expr": "sum(irate(node_network_transmit_bytes_total[1m])) by (instance) * 8",
     "legendFormat": "{{instance}} out"
    }
   ]
  },
  {
   "title": "Disk IOps",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "iops", "label": "IO read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{device=~\"[a-z]*[a-z]\"}[1m])",
     "legendFormat": "{{instance}} - {{device}} - Reads"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{device=~\"[a-z]*[a-z]\"}[1m])",
     "legendFormat": "{{instance}} - {{device}} - Writes"
    }
   ]
  },
  {
   "title": "Linux Nodes Disk Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100.0 - 100 * ((node_filesystem_avail_bytes{mountpoint=~\"/\", device=~\"rootfs\"} / 1000 / 1000 ) / (node_filesystem_size_bytes{mountpoint=~\"/\", device=~\"rootfs\"}  / 1024 / 1024))",
     "legendFormat": "{{instance}} - {{mountpoint}}"
    },
    {
     "expr": "100.0 - 100 * ((node_filesystem_avail_bytes{mountpoint=~\"/opt\"} / 1000 / 1000 ) / (node_filesystem_size_bytes{mountpoint=~\"/opt\"}  / 1024 / 1024))",
     "legendFormat": "{{instance}} - {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Nginx Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nginx_connections_processed_total[1m])) by (instance)",
     "legendFormat": "{{instance}} {{ stage }}"
    }
   ]
  },
  {
   "title": "MySQL Slave Behind Master",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 41 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "mysql_slave_status_seconds_behind_master",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}