{
 "title": "Nginx Overview",
 "description": "Shows stats built from the Prometheus Nginx plugin.",
 "tags": [ "nginx" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(nginx_up, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Status (Last 30s)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nginx_up{instance=~\"$instance.*\"})"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nginx_connections_current{state=\"active\", instance=~\"$instance.*\"})"
    }
   ]
  },
  {
   "title": "Waiting connections",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nginx_connections_current{state=\"waiting\", instance=~\"$instance.*\"})"
    }
   ]
  },
  {
   "title": "Reading connections",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nginx_connections_current{state=\"reading\", instance=~\"$instance.*\"})"
    }
   ]
  },
  {
   "title": "Writing connections",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nginx_connections_current{state=\"writing\", instance=~\"$instance.*\"})"
    }
   ]
  },
  {
   "title": "Exporter Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(time() - process_start_time_seconds{job=~\"(?i:(nginx.*))\", instance=~\"$instance.*\"})"
    }
   ]
  },
  {
   "title": "Processed connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(nginx_connections_processed_total{instance=~\"$instance.*\"}[1m])",
     "legendFormat": "{{instance}} {{ stage }}"
    }
   ]
  }
 ]
}