{
 "title": "Nginx Requests",
 "description": "Shows stats built from the Prometheus Nginx plugin.",
 "tags": [ "nginx" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "Server",
    "query": "label_values(nginx_http_request_time_sum, instance)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(nginx_http_request_time_sum, host)"
   },
   { "name": "status", "label": "Status", "query": "label_values(status)" },
   {
    "name": "timeRange",
    "label": "TimeRange",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Apdex",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(rate(nginx_http_request_time_bucket{instance=~\"$server\",host=~\"$host\",status=~\"$status\",le=\"00.010\"}[1m]))+sum(rate(nginx_http_request_time_bucket{instance=~\"$server\",host=~\"$host\",status=~\"$status\",le=\"00.010\"}[1m]))) / 2 / sum(rate(nginx_http_request_time_count{instance=~\"$server\",host=~\"$host\",status=~\"$status\"}[1m]))"
    }
   ]
  },
  {
   "title": "Hosts",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(sum(nginx_http_request_time_count{instance=~\"$server\",host=~\"$host\",status=~\"$status\"}) by (host))"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(nginx_http_connections{instance=~\"$server\"})"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(nginx_http_requests{instance=~\"$server\",host=~\"$host\",status=~\"$status\"}[$timeRange]))"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(nginx_http_request_bytes_sent{instance=~\"$server\",host=~\"$host\",status=~\"$status\"}[$timeRange]))"
    }
   ]
  },
  {
   "title": "Upstream Requests",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(nginx_http_upstream_requests{instance=~\"$server\"}[$timeRange]))"
    }
   ]
  },
  {
   "title": "HTTP Responses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nginx_http_requests{instance=~\"$server\",host=~\"$host\",status=~\"$status\"}[5m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_http_request_time_sum{instance=~\"$server\",host=~\"$host\",status=~\"$status\"}[1m])) / sum(rate(nginx_http_request_time_count{instance=~\"$server\",host=~\"$host\",status=~\"$status\"}[1m]))",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nginx_http_request_bytes_sent{instance=~\"$server\",host=~\"$host\",status=~\"$status\"}[5m]))",
     "legendFormat": "bytes"
    }
   ]
  },
  {
   "title": "Upstream Response",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nginx_http_upstream_requests{instance=~\"$server\"}[1m])) by (addr)",
     "legendFormat": "{{addr}}"
    }
   ]
  },
  {
   "title": "Upstream Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_http_upstream_response_time_sum{instance=~\"$server\"}[1m])) by (addr) / sum(rate(nginx_http_upstream_response_time_count{instance=~\"$server\"}[1m])) by (addr)",
     "legendFormat": "{{addr}}"
    }
   ]
  },
  {
   "title": "Upstream Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nginx_http_upstream_bytes_received{instance=~\"$server\"}[5m])) by (addr)",
     "legendFormat": "{{addr}}"
    }
   ]
  },
  {
   "title": "HTTP Requests By Host",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(20, sum(increase(nginx_http_requests{instance=~\"$server\",host=~\"$host\",status=~\"$status\"}[1m])) by (host))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Bandwidth By Host",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(increase(nginx_http_request_bytes_sent{instance=~\"$server\",host=~\"$host\",status=~\"$status\"}[5m])) by (host))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Response time by Host",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(20, sum(rate(nginx_http_request_time_sum{instance=~\"$server\",host=~\"$host\",status=~\"$status\"}[1m])) by (host) / sum(rate(nginx_http_request_time_count{instance=~\"$server\",host=~\"$host\",status=~\"$status\"}[1m])) by (host))",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}