{
 "title": "Node Dashboard",
 "description": "Batch of nearly all metrics values exported by Prometheus and Node Exporter.",
 "tags": [ "node" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(node_boot_time_seconds, instance)"
   },
   {
    "name": "device",
    "query": "label_values(node_network_receive_bytes_total, device)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(node_boot_time_seconds, job)"
   },
   {
    "name": "timeRange",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "CPU / Memory / Disk Gauge", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Busy",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=~\"$node\",job=~\"$job\"}) by (instance, cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$node\",job=~\"$job\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=~\"$node\",job=~\"$job\"}) by (instance, cpu))"
    }
   ]
  },
  {
   "title": "CPU System Load (1m avg)",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together (1 min average)",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_load1{instance=~\"$node\",job=~\"$job\"}) /  count(count(node_cpu_seconds_total{instance=~\"$node\",job=~\"$job\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "CPU System Load (5m avg)",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_load5{instance=~\"$node\",job=~\"$job\"}) /  count(count(node_cpu_seconds_total{instance=~\"$node\",job=~\"$job\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Used SWAP",
   "type": "singlestat",
   "description": "Used Swap",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum((node_memory_SwapTotal_bytes{instance=~\"$node\",job=~\"$job\"} - node_memory_SwapFree_bytes{instance=~\"$node\",job=~\"$job\"}) / (node_memory_SwapTotal_bytes{instance=~\"$node\",job=~\"$job\"} )) * 100"
    }
   ]
  },
  {
   "title": "Used Root FS",
   "type": "singlestat",
   "description": "The root filesystem is the filesystem that is contained on the same partition on which the root directory is located",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - avg((node_filesystem_avail_bytes{instance=~\"$node\",job=~\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=~\"$node\",job=~\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Disk space",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "min((node_filesystem_size_bytes{fstype=~\"xfs|ext4\",instance=~\"$node\"} - node_filesystem_free_bytes{fstype=~\"xfs|ext4\",instance=~\"$node\"} )/ node_filesystem_size_bytes{fstype=~\"xfs|ext4\",instance=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Used RAM Memory",
   "type": "singlestat",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - avg((node_memory_MemAvailable_bytes{instance=~\"$node\",job=~\"$job\"} * 100) / node_memory_MemTotal_bytes{instance=~\"$node\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Available memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg( (node_memory_MemFree_bytes{instance=~\"$node\"} + node_memory_Cached_bytes{instance=~\"$node\"} + node_memory_Slab_bytes{instance=~\"$node\"} + node_memory_Buffers_bytes{instance=~\"$node\"} ) / node_memory_MemTotal_bytes{instance=~\"$node\"}) * 100"
    }
   ]
  },
  {
   "title": "Load",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_load1{instance=~\"$node\"} / count by(job, instance)(count by(job, instance, cpu)(node_cpu_seconds_total{instance=~\"$node\"})))"
    }
   ]
  },
  {
   "title": "CPU / Memory / Disk Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 10 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$node\",job=~\"$job\"}) by (instance, cpu))"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "System uptime",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 10 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(node_time_seconds{instance=~\"$node\",job=~\"$job\"} - node_boot_time_seconds{instance=~\"$node\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "System Load (1m avg)",
   "type": "singlestat",
   "description": "System Load (1m avg)",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 10 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_load1{instance=~\"$node\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "System Load (5m avg)",
   "type": "singlestat",
   "description": "System Load (5m avg)",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 10 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_load5{instance=~\"$node\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "singlestat",
   "description": "Total RAM",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 13 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$node\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Disk Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 13 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{instance=~\"$node\", device=~\"/dev/.*\"})"
    }
   ]
  },
  {
   "title": "Total RootFS",
   "type": "singlestat",
   "description": "Total RootFS",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 13 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{instance=~\"$node\",job=~\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Total SWAP",
   "type": "singlestat",
   "description": "Total SWAP",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 13 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_memory_SwapTotal_bytes{instance=~\"$node\",job=~\"$job\"})"
    }
   ]
  },
  { "title": "CPU / Memory Graph", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg without (cpu)(irate(node_cpu_seconds_total{instance=~\"$node\",job=~\"$job\",mode!=\"idle\"}[5m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\",job=~\"$job\"} - node_memory_MemFree{instance=~\"$node:$port\",job=~\"$job\"} - (node_memory_Cached{instance=~\"$node:$port\",job=~\"$job\"} + node_memory_Buffers{instance=~\"$node:$port\",job=~\"$job\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$node\",job=~\"$job\"} + node_memory_Buffers{instance=~\"$node:$port\",job=~\"$job\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~\"$node\",job=~\"$job\"} - node_memory_SwapFree{instance=~\"$node:$port\",job=~\"$job\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Percentage" }
   ],
   "targets": [
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"system\",instance=~\"$node\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "System - Processes executing in kernel mode"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='user',instance=~\"$node\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "User - Normal processes executing in user mode"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='nice',instance=~\"$node\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Nice - Niced processes executing in user mode"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$node\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Idle - Waiting for something to happen"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='iowait',instance=~\"$node\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Iowait - Waiting for I/O to complete"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='irq',instance=~\"$node\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Irq - Servicing interrupts"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='softirq',instance=~\"$node\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Softirq - Servicing softirqs"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='steal',instance=~\"$node\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Steal - Time spent in other operating systems when running in a virtualized environment"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='guest',instance=~\"$node\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Guest - Time spent running a virtual CPU for a guest operating system"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\",job=~\"$job\"} - node_memory_MemFree_bytes{job='node',instance='$instance'} - node_memory_Buffers_bytes{job='node',instance='$instance'} - node_memory_Cached_bytes{job='node',instance='$instance'}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Memory Stack",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\",job=~\"$job\"} - node_memory_MemFree_bytes{instance=~\"$node\",job=~\"$job\"} - node_memory_Buffers_bytes{instance=~\"$node\",job=~\"$job\"} - node_memory_Cached_bytes{instance=~\"$node\",job=~\"$job\"} - node_memory_Slab_bytes{instance=~\"$node\",job=~\"$job\"} - node_memory_PageTables_bytes{instance=~\"$node\",job=~\"$job\"} - node_memory_SwapCached_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "Apps - Memory used by user-space applications"
    },
    {
     "expr": "node_memory_PageTables_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "PageTables - Memory used to map between virtual and physical memory addresses"
    },
    {
     "expr": "node_memory_SwapCached_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "SwapCache - Memory that keeps track of pages that have been fetched from swap but not yet been modified"
    },
    {
     "expr": "node_memory_Slab_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "Slab - Memory used by the kernel to cache data structures for its own use (caches like inode, dentry, etc)"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "Cache - Parked file data (file content) cache"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "Buffers - Block device (e.g. harddisk) cache"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "Unused - Free memory unasigned"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~\"$node\",job=~\"$job\"} - node_memory_SwapFree{instance=~\"$node\",job=~\"$job\"})",
     "legendFormat": "Swap - Swap space used"
    },
    {
     "expr": "node_memory_HardwareCorrupted_bytes{instance=~\"$node\",job=~\"$job\"}",
     "legendFormat": "Harware Corrupted - Amount of RAM that the kernel identified as corrupted / not working"
    }
   ]
  },
  {
   "title": "CPU Basic",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"system\",instance=~\"$node\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='user',instance=~\"$node\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='iowait',instance=~\"$node\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=~\".*irq\",instance=~\"$node\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (rate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=~\"$node\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=~\"$node\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Disk Graph",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Space Used",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{instance=~\"$node\",job=~\"$job\",device!~'rootfs'} - node_filesystem_avail_bytes{instance=~\"$node\",job=~\"$job\",device!~'rootfs'}",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "I/O Usage Read / Write",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{instance=~\"$node\",job=~\"$job\",device=~\"[a-z]*[a-z]\"}[5m])",
       "legendFormat": "{{device}} - Successfully read bytes"
      },
      {
       "expr": "irate(node_disk_written_bytes_total{instance=~\"$node\",job=~\"$job\",device=~\"[a-z]*[a-z]\"}[5m])",
       "legendFormat": "{{device}} - Successfully written bytes"
      }
     ]
    },
    {
     "title": "Filesystem Fullness",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "1 - node_filesystem_free_bytes{instance=~\"$node\",job=~\"$job\",fstype!='rootfs',mountpoint!~'/images/',mountpoint!=''} / node_filesystem_size_bytes{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Disk Space Used",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 39 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{instance=~\"$node\",job=~\"$job\",device!~'rootfs'} - node_filesystem_avail_bytes{instance=~\"$node\",job=~\"$job\",device!~'rootfs'}",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Traffic (eth0)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "bps", "label": "bps in (-) / bps out (+)" }
     ],
     "targets": [
      {
       "expr": "sum(irate(node_network_receive_bytes_total{device=~\"$device\",instance=~\"$node\",job=~\"$job\"}[1m])) * 8",
       "legendFormat": "in"
      },
      {
       "expr": "sum(irate(node_network_transmit_bytes_total{device=~\"$device\",instance=~\"$node\",job=~\"$job\"}[1m])) * 8",
       "legendFormat": "out"
      }
     ]
    },
    {
     "title": "Network Utillization",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "bytes", "label": "bits in (-) / bits out (+)" }
     ],
     "targets": [
      {
       "expr": "sum(increase(node_network_receive_bytes_total{device=~\"$device\",instance=~\"$node\"}[1m]))",
       "legendFormat": "in"
      },
      {
       "expr": "sum(increase(node_network_transmit_bytes_total{device=~\"$device\",instance=~\"$node\"}[1m]))",
       "legendFormat": "out"
      }
     ]
    },
    {
     "title": "Traffic In",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 26 },
     "format": "decbytes",
     "valueName": "max",
     "targets": [
      {
       "expr": "sum(increase(node_network_receive_bytes_total{device=~\"$device\",instance=~\"$node\"}[$timeRange]))"
      }
     ]
    },
    {
     "title": "Traffic Out",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 26 },
     "format": "bytes",
     "valueName": "max",
     "targets": [
      {
       "expr": "sum(increase(node_network_transmit_bytes_total{device=~\"$device\",instance=~\"$node\"}[$timeRange]))"
      }
     ]
    },
    {
     "title": "Netstat: TCP",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(node_netstat_Tcp_CurrEstab{instance=~\"$node\"})",
       "legendFormat": "established"
      },
      {
       "expr": "sum(node_netstat_Tcp_ActiveOpens{instance=~\"$node\"})",
       "legendFormat": "activeOpens"
      },
      {
       "expr": "sum(node_netstat_Tcp_PassiveOpens{instance=~\"$node\"})",
       "legendFormat": "passiveOpens"
      },
      {
       "expr": "sum(node_netstat_Tcp_EstabResets{instance=~\"$node\"})",
       "legendFormat": "estabResets"
      },
      {
       "expr": "sum(node_netstat_Tcp_AttemptFails{instance=~\"$node\"})",
       "legendFormat": "attemptfails"
      },
      {
       "expr": "sum(node_netstat_Tcp_RetransSegs{instance=~\"$node\"})",
       "legendFormat": "retransSegs"
      }
     ]
    },
    {
     "title": "Netstat: UDP",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(node_netstat_Udp_InDatagrams{instance=~\"$node\"}[5m]))",
       "legendFormat": "Udp_InDatagrams"
      },
      {
       "expr": "sum(irate(node_netstat_Udp_InErrors{instance=~\"$node\"}[5m]))",
       "legendFormat": "Udp_InErrors"
      },
      {
       "expr": "sum(irate(node_netstat_Udp_OutDatagrams{instance=~\"$node\"}[5m]))",
       "legendFormat": "Udp_OutDatagrams"
      },
      {
       "expr": "sum(irate(node_netstat_Udp_NoPorts{instance=~\"$node\"}[5m]))",
       "legendFormat": "Udp_NoPorts"
      },
      {
       "expr": "sum(irate(node_netstat_Udp_InCsumErrors{instance=~\"$node\"}[5m]))",
       "legendFormat": "Udp_InCsumErrors"
      },
      {
       "expr": "sum(irate(node_netstat_Udp_RcvbufErrors{instance=~\"$node\"}[5m]))",
       "legendFormat": "Udp_RcvbufErrors"
      },
      {
       "expr": "sum(irate(node_netstat_Udp_SndbufErrors{instance=~\"$node\"}[5m]))",
       "legendFormat": "Udp_SndbufErrors"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Traffic Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Traffic by Packets",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "pps", "label": "Packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_packets_total{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "{{device}} - Receive"
      },
      {
       "expr": "irate(node_network_transmit_packets_total{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "{{device}} - Transmit"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(irate(node_network_receive_bytes_total{instance=~\"$node\"}[5m]))",
       "legendFormat": "RECEIVED"
      },
      {
       "expr": "- sum(irate(node_network_transmit_bytes_total{instance=~\"$node\"}[5m]))",
       "legendFormat": "SENT"
      }
     ]
    },
    {
     "title": "Network Traffic Drop",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "pps", "label": "Packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_drop_total{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "{{device}} - Receive drop"
      },
      {
       "expr": "irate(node_network_transmit_drop_total{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "{{device}} - Transmit drop"
      }
     ]
    },
    {
     "title": "Network Traffic Errors",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 56 },
     "yaxes": [
      { "format": "pps", "label": "Packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_errs_total{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "{{device}} - Receive errors"
      },
      {
       "expr": "irate(node_network_transmit_errs_total{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "{{device}} - Rransmit errors"
      }
     ]
    },
    {
     "title": "TCP Connections",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "short", "label": "Connections" }
     ],
     "targets": [
      {
       "expr": "node_netstat_Tcp_CurrEstab{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "CurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE- WAIT"
      },
      {
       "expr": "node_netstat_Tcp_InErrs{instance=~\"$node\",job=~\"$job\"}",
       "legendFormat": "InErrs"
      }
     ]
    },
    {
     "title": "Network Traffic Fifo",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 66 },
     "yaxes": [
      { "format": "pps", "label": "Packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_fifo_total{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "{{device}} - Receive fifo"
      },
      {
       "expr": "irate(node_network_transmit_fifo_total{instance=~\"$node\",job=~\"$job\"}[5m])",
       "legendFormat": "{{device}} - Transmit fifo"
      }
     ]
    }
   ]
  },
  {
   "title": "Prometheus / Node / Scraps  Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Exporter Build Info",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 77 },
     "targets": [
      {
       "expr": "prometheus_build_info",
       "legendFormat": "Prometheus Version: {{version}}"
      },
      {
       "expr": "node_exporter_build_info",
       "legendFormat": "Node-Exporter Version: {{version}}"
      }
     ]
    },
    {
     "title": "Scrape Duration",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 84 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "topk(5, max(scrape_duration_seconds) by (job))",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "scrape_collector_duration",
     "type": "graph",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 93 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "node_scrape_collector_duration_seconds{job=\"node\",instance=~\"$node\"}",
       "legendFormat": "{{collector}}"
      }
     ]
    }
   ]
  }
 ]
}