{
 "title": "Node - Network Overview",
 "description": "Dashboard to view multiple servers",
 "tags": [
  "node",
  "network"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(node_boot_time_seconds, instance)"
   },
   {
    "name": "device",
    "query": "label_values(node_network_receive_bytes_total, device)"
   },
   {
    "name": "timeRange",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Traffic Out",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "format": "bytes",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{device=~\"$device\",instance=~\"$node\"}[$timeRange]))"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "bps", "label": "bps in (-) / bps out (+)" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{device=~\"$device\",instance=~\"$node\"}[5m])) * 8",
     "legendFormat": "in"
    },
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{device=~\"$device\",instance=~\"$node\"}[5m])) * 8",
     "legendFormat": "out"
    }
   ]
  },
  {
   "title": "Network Utillization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "bytes", "label": "bits in (-) / bits out (+)" }
   ],
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{device=~\"$device\",instance=~\"$node\"}[5m]))",
     "legendFormat": "in"
    },
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{device=~\"$device\",instance=~\"$node\"}[5m]))",
     "legendFormat": "out"
    }
   ]
  },
  {
   "title": "Traffic In",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
   "format": "decbytes",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{device=~\"$device\",instance=~\"$node\"}[$timeRange]))"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_load1{instance=~\"$node\"})",
     "legendFormat": "load1"
    },
    {
     "expr": "sum(node_load5{instance=~\"$node\"})",
     "legendFormat": "load5"
    },
    {
     "expr": "sum(node_load15{instance=~\"$node\"})",
     "legendFormat": "load15"
    }
   ]
  },
  {
   "title": "Network Traffic by Packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "pps", "label": "Packets out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_packets_total{instance=~\"$node\",device=~\"$device\"}[5m])",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_packets_total{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "Netstat: TCP",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_netstat_Tcp_CurrEstab{instance=~\"$node\"})",
     "legendFormat": "established"
    },
    {
     "expr": "sum(irate(node_netstat_Tcp_ActiveOpens{instance=~\"$node\"}[$__interval]))",
     "legendFormat": "activeOpens"
    },
    {
     "expr": "sum(irate(node_netstat_Tcp_PassiveOpens{instance=~\"$node\"}[$__interval]))",
     "legendFormat": "passiveOpens"
    },
    {
     "expr": "sum(irate(node_netstat_Tcp_EstabResets{instance=~\"$node\"}[$__interval]))",
     "legendFormat": "estabResets"
    },
    {
     "expr": "sum(irate(node_netstat_Tcp_AttemptFails{instance=~\"$node\"}[$__interval]))",
     "legendFormat": "attemptfails"
    },
    {
     "expr": "sum(irate(node_netstat_Tcp_RetransSegs{instance=~\"$node\"}[$__interval]))",
     "legendFormat": "retransSegs"
    }
   ]
  },
  {
   "title": "Netstat: UDP",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_netstat_Udp_InDatagrams{instance=~\"$node\"}[15s]))",
     "legendFormat": "Udp_InDatagrams"
    },
    {
     "expr": "sum(irate(node_netstat_Udp_InErrors{instance=~\"$node\"}[15s]))",
     "legendFormat": "Udp_InErrors"
    },
    {
     "expr": "sum(irate(node_netstat_Udp_OutDatagrams{instance=~\"$node\"}[15s]))",
     "legendFormat": "Udp_OutDatagrams"
    },
    {
     "expr": "sum(irate(node_netstat_Udp_NoPorts{instance=~\"$node\"}[15s]))",
     "legendFormat": "Udp_NoPorts"
    },
    {
     "expr": "sum(irate(node_netstat_Udp_InCsumErrors{instance=~\"$node\"}[15s]))",
     "legendFormat": "Udp_InCsumErrors"
    },
    {
     "expr": "sum(irate(node_netstat_Udp_RcvbufErrors{instance=~\"$node\"}[15s]))",
     "legendFormat": "Udp_RcvbufErrors"
    },
    {
     "expr": "sum(irate(node_netstat_Udp_SndbufErrors{instance=~\"$node\"}[15s]))",
     "legendFormat": "Udp_SndbufErrors"
    }
   ]
  },
  {
   "title": "Conntrack",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_nf_conntrack_entries_limit{instance=~\"$node\"}) - sum(node_nf_conntrack_entries{instance=~\"$node\"})",
     "legendFormat": "free"
    },
    {
     "expr": "sum(node_nf_conntrack_entries_limit{instance=~\"$node\"})",
     "legendFormat": "limit"
    }
   ]
  }
 ]
}