{
 "title": "PHP-FPM",
 "description": "PHP-FPM detailed page for single FPM pool.",
 "tags": [ "php-fpm" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Host",
    "query": "label_values(phpfpm_accepted_conn, instance)"
   },
   { "name": "Interval", "label": "Time Interval", "query": "20s,1m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  { "title": "PHP FPM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PHP-FPM Status",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(phpfpm_up{instance=~\"^$Host$\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 5, "w": 15, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "phpfpm_start_since{instance=~\"^$Host$\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Workers  Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum( phpfpm_active_processes{instance=~\"^$Host$\"}) / sum(phpfpm_max_active_processes{instance=~\"^$Host$\"} )"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Accepted Connections Rate",
   "type": "graph",
   "description": "Total number of accepted connections",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(phpfpm_accepted_conn{instance=~\"^$Host$\"}[$Interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Listen Queue Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "phpfpm_listen_queue{instance=~\"^$Host$\"}",
     "legendFormat": "{{instance}} Queue"
    },
    {
     "expr": "phpfpm_listen_queue_len{instance=~\"^$Host$\"}",
     "legendFormat": "{{instance}} Queue Length"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "phpfpm_max_active_processes{instance=~\"^$Host$\"}",
     "legendFormat": "{{instance}} Max Active"
    },
    {
     "expr": "phpfpm_active_processes{instance=~\"^$Host$\"}",
     "legendFormat": "{{instance}} Active"
    },
    {
     "expr": "phpfpm_idle_processes{instance=~\"^$Host$\"}",
     "legendFormat": "{{instance}} Idle"
    }
   ]
  },
  {
   "title": "Slow Requests Rate",
   "type": "graph",
   "description": "Number of requests that exceed request_slowlog_timeout",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(phpfpm_slow_requests{instance=~\"^$Host$\"}[$Interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}